// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-oMmvrcsSDtrJz7gj_QqUVBVzve-Y8OA',
    appId: '1:535271060743:web:4d6d26c5c6e50c579081a2',
    messagingSenderId: '535271060743',
    projectId: 'indagoapp-b8aa4',
    authDomain: 'indagoapp-b8aa4.firebaseapp.com',
    storageBucket: 'indagoapp-b8aa4.firebasestorage.app',
    measurementId: 'G-DXZ19565LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZOKa8xOie-wBxFBwshpKDO5fKNAUeDg',
    appId: '1:535271060743:android:5e4c38de6ffec5709081a2',
    messagingSenderId: '535271060743',
    projectId: 'indagoapp-b8aa4',
    storageBucket: 'indagoapp-b8aa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXl-FpJyccK9SU-q2ZfroOFNR8T0qCHg',
    appId: '1:535271060743:ios:9aca30a25658ab6c9081a2',
    messagingSenderId: '535271060743',
    projectId: 'indagoapp-b8aa4',
    storageBucket: 'indagoapp-b8aa4.firebasestorage.app',
    iosBundleId: 'com.example.indagoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSXl-FpJyccK9SU-q2ZfroOFNR8T0qCHg',
    appId: '1:535271060743:ios:9aca30a25658ab6c9081a2',
    messagingSenderId: '535271060743',
    projectId: 'indagoapp-b8aa4',
    storageBucket: 'indagoapp-b8aa4.firebasestorage.app',
    iosBundleId: 'com.example.indagoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-oMmvrcsSDtrJz7gj_QqUVBVzve-Y8OA',
    appId: '1:535271060743:web:2715838b2982a8c79081a2',
    messagingSenderId: '535271060743',
    projectId: 'indagoapp-b8aa4',
    authDomain: 'indagoapp-b8aa4.firebaseapp.com',
    storageBucket: 'indagoapp-b8aa4.firebasestorage.app',
    measurementId: 'G-N6X1DHXY95',
  );
}
